apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-cloud-app
  name: spring-cloud-app
spec:
  selector:
    app: spring-cloud-app
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
